#ddev-generated
RUN curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/073500cbdf8ba211e5115fc6e51411cf2468fc5b/install.sh | HOME=/opt/zoxide bash && cp -R /opt/zoxide/.local/* /usr/local && rm -fr /opt/zoxide
