#ddev-generated
RUN curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/e3ab444976c49a518469bcc30c74b6780cd33fde/install.sh | HOME=/opt/zoxide bash && cp -R /opt/zoxide/.local/* /usr/local && rm -fr /opt/zoxide
# It includes a patch of my own: https://github.com/junegunn/fzf/pull/3439
RUN git clone --depth 1 https://github.com/junegunn/fzf.git /opt/fzf && cd /opt/fzf && git reset --hard eb4bbf32948303e326a2791c6a875f32d7b5c97f && wget https://patch-diff.githubusercontent.com/raw/junegunn/fzf/pull/3439.patch -O - | patch && /opt/fzf/install
